### ISSUE TITLE
Add a fallback hero image to articles (only, not home page, etc) that don't have one assigned. 

### ISSUE THREAD

**Issue by budparr** [Frontmatter/cureforward#15]
Image attached (I'll add a mockup for it in a moment):
[noillustration.svg | uploaded via ZenHub](https://files.zenhub.io/55f70bb2712977ea7e27f81c)

[referencelink.svg | uploaded via ZenHub](https://files.zenhub.io/55f70bb2712977ea7e27f81d)

**Comment by budparr** [comment]
example of a story with a "no-illustration" fallback.
![egfr2-07](https://cloud.githubusercontent.com/assets/115347/9857647/b141aaa0-5ae9-11e5-85a0-b5a9027c66fa.png)

**Comment by budparr** [comment]
Note that the reference link is for reference articles on the bottom of the page. I'm going to put it in a separate issue.

**Comment by AdamChlan** [comment]
@budparr the current hero.html partial has a fallback pointing to an image at http://lh3.googleusercontent.com. Do you want the new image to be hosted there or just in the static folder. If on google, I'm not sure how to get the file up there.

**Comment by budparr** [comment]
@AdamChlan Just the new image, but the home page (as well as other non-article pages) need their own. So the one that's there now is just for the home page.

**Comment by AdamChlan** [comment]
@budparr gotcha. I didn't see the hero-article.html at first. What are your thoughts on SVG fallback for this? Is that something you want to have set up?

**Comment by budparr** [comment]
@AdamChlan You mean a fallback for the SVG? I think support is pretty good for it these days: http://caniuse.com/#feat=svg What do you think?

**Comment by AdamChlan** [comment]
@budparr I agree it's good. Now that IE 8 is pretty much dead, it's been nice to leave some old techniques in the dust.

**Comment by budparr** [comment]
Hallelujah to that!

**Comment by budparr** [comment]
Quick note. Have a look at the mockup and make the height of the hero image the same height - I think it's too tall right now. (this is a priority over the further reading)

**Comment by AdamChlan** [comment]
@budparr will fix it up ASAP.
