### ISSUE TITLE
Use Reference Link background image for articles at the end of an article.

### ISSUE THREAD

**Issue by budparr** [Frontmatter/cureforward#16]
These are specifically the links at further reading part at the bottom "Sample Reference Link" in the mockup and the further reading in the CMS

<img width="575" alt="screen shot 2015-09-14 at 4 49 32 pm" src="https://cloud.githubusercontent.com/assets/115347/9861495/ab2cf478-5b00-11e5-948e-bd319f78788f.png">

[referencelink.svg | uploaded via ZenHub](https://files.zenhub.io/55f70eba712977ea7e27f849)

![genestory_grid_padding-05](https://cloud.githubusercontent.com/assets/115347/9857829/fc48ba60-5aea-11e5-8394-4197a0afa678.png)

**Comment by AdamChlan** [comment]
@budparr do you want the image and the title to be active links to the articles?

**Comment by budparr** [comment]
Do you mean as opposed to the just the title? Yes, I think, though no one specified, that they both should be links.

**Comment by AdamChlan** [comment]
@budparr when you get a chance can you let me know if I'm on the right track with the further reading area? The mockup content doesn't exactly match what is in the CMS at this point. Do we still want to show the article source as opposed to the "Read and discuss notes that went into writing this Gene story" that shows in the mockup?

**Comment by budparr** [comment]
They just need to be a bit smaller (*note below), the background colors randomized (see the other issue), and the links fixed, but otherwise, yes, I think you've got it. There are two sources for further reading: internal links, which haven't been added, and these external links.

* they look way too big. The mockup shows them not spanning the entire grid, which, unless we have the width of the grid wrong, seems wrong to me. why don't we try putting three across and I'll check in with the designer on it.

**Comment by AdamChlan** [comment]
@budparr sounds good. I'll jump back onto this next.

**Comment by AdamChlan** [comment]
@budparr I'm getting ready to push this new branch for review. Can you confirm which option we want for the text under the headline?

a) leave the source field from the CMS
or the text
b) "Read and discuss notes that went into writing this Gene Story"

**Comment by budparr** [comment]
Source field (the "Read..." Is dummy text).
