### ISSUE TITLE
Randomize colors of fact boxes and reference link

### ISSUE THREAD

**Issue by budparr** [Frontmatter/cureforward#17]
> The Brand Primary color can and should be randomized on gene stories and reference links to create variety.

> Colors to use from the style guide:
Brand Primary
Primary Green
Accent Blue
Accent Magenta
Medium Grey 2

**Comment by budparr** [comment]
@AdamChlan I'm not going to assign this to you because it seems like a low priority at the moment, but keep it in the back of your mind. I take the comment above (quoted from an email from the designer) that it means to randomize the factbox colors, as well as the background color on reference articles(below the article where we're using an svg image for them)

**Comment by AdamChlan** [comment]
@budparr I was hoping to do something like what is shown here:
http://stackoverflow.com/questions/26922336/random-color-from-array-in-sass

But they are not really siblings, so that won't work. I may just write a bit of jQuery to assign a random class to the HREF and style against that.

**Comment by budparr** [comment]
why aren't they siblings?

**Comment by AdamChlan** [comment]
@budparr figured it out. will push up in a bit.

**Comment by budparr** [comment]
awesome

**Comment by AdamChlan** [comment]
@budparr I don't know if this info gets emailed to you, but here is my comment on the commit I just pushed...

This randomizes the background colors of the reference link images. The
one caveat for this is that since the SCSS is compiled it’s not random
on refresh. Each nth-child receives a background color when the SCSS
compiles, and that remains the same until a new css file would be
pushed up. If we want it to be truly random on every page/refresh, I
think we’d need to use some JS to randomize the classes, and style
against that.

fixes #17

**Comment by budparr** [comment]
no need for random on refresh. I'll have a look this morning (got a bit up yesterday)

**Comment by AdamChlan** [comment]
Cool. Is there a limit to the amount of reference links they can add per article? If so, we can set $repeat to that number. Right now it's set to 20 which means there are 20 selectors generated. Do you think that will be enough if there are no limits specified in the CMS?

**Comment by budparr** [comment]
I think 20 should be enough, though that's an editorial decision, not
design.

**Comment by budparr** [comment]
@AdamChlan Does this what you've done so far affect the fact boxes as well, or just so far the recommended reading boxes?

**Comment by AdamChlan** [comment]
@budparr just recommended reading. the fact boxes have their own styles.

**Comment by budparr** [comment]
@AdamChlan Okay. Did you get a sense from the mockups that the fact box colors should be stable, or would the above statement seem to apply to fact boxes as well? I'm trying to open up more communication with the designer, but they seem to be pretty busy or something.

**Comment by AdamChlan** [comment]
@budparr it seems like the existing code achieves what they are looking for. The only difference is that the fact boxes colors would not change on a CSS rebuild. In my opinion, that's a good thing if there is a limit of 6 fact boxes. This way, there is no chance of them ever being the same color.

**Comment by budparr** [comment]
@AdamChlan Sounds good. I'll leave this closed then.
